on:
  push:
    branches: main
  pull_request:

jobs:
  env_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print env info
        run: echo "$RUNNER_OS"
  
  
