name: Try out variables and context
on:
  workflow_dispatch:

env:
  workfl_var: I-am-a-workflow-var
  
jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      job_var: I-am-a-job-var
    steps:
      - name: default-env-variables
        run: echo "$GITHUB_ACTOR printed this default env variable"
        
      - name: Print out custom env variables
        run: echo "Who are we? $workfl_var $job_var $step_var"
        env:
          step_var: I-am-a-step-var

  context:
    if: github.ref_name == 'main'
    runs-on: ubuntu-slim
    steps:
      - name: Here comes context
        run: |
          echo "${{  github.actor }} tiggered workflow ${{ github.workflow }} manually, alias ${{ github.event_name }} and here comes a workflow custom var $workfl_var."
    
    
      
